### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [8]:
lista1=[]
for i in range(1,21):
    lista1.append(i)

print(lista1)

lista11 = [i for i in range(1,21)]
print(lista11)

lista2=[]
for i in range(1,21):
    if i%2==1:
        lista2.append(i)
print(lista2)

lista22=[i for i in range(1,21) if i%2==1]
print(lista22)

lista3=[]
for i in range(1,21):
    if i%2==1:
        lista3.append(i+1)
    else:
        lista3.append(i-1)
print(lista3)
lista33=[i+1  if i%2==1 else i-1 for i in range(1,21)]
print(lista33)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20, 19]
[2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15, 18, 17, 20, 19]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [7]:
import numpy as np

primi=np.array([1,2,3,5,7])
print(len(primi))
print(primi.size)

print(primi.dtype)

def eprimo(x, y):
    if x==1 or y==1:
        return True
    elif x%y==0:
        return False
    else:
        return eprimo(x, y-1)

primi2=np.array([i for i in range(1,10) if eprimo(i,i-1)])
print(primi2)


5
5
int64
[1 2 3 5 7]


In [ ]:
import numpy as np

a=np.array(range(20))
b=np.random.choice(a, size=10,replace=True)
c=np.array(a[::-1])
print(a)
print(b)
print(c)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[17  1 19 10  1 16  3 17 12  4]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
