### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [32]:
import numpy as np

def eprimo(x,y):
    if x==1 or y==1:        #se y=1 vuol dire che prima non ha trovato nessuma divisione che desse risultato positivo, quindi x è primo
        return True
    elif x%y==0:            #se x è divisibile per y, allora x non è primo
        return False
    else:
        return eprimo(x,y-1)    #ricorsione con y-1

primi = np.array([i for i in range(0,20) if eprimo(i, i-1)])   #aggiunge i  numeri da 0 a 20 solo se la funzione eprimo ritorna True
print(primi)

print(primi[primi>10])
print(primi[primi%2==0])


[ 1  2  3  5  7 11 13 17 19]
[11 13 17 19]
[2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [33]:
import numpy as np
a = np.arange(1,21).reshape(5,4)    #numeri da 1 a 21 (escluso) in una matrice 5x4
b = np.array(a[[1,3],:])            #prende la seconda e la quarta della matrice a
c = np.array(a[3, :])               #prende la riga 3 della matrice a
print(a, "\n\n", b, "\n\n", c)

print("\n",a/c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

 [[ 5  6  7  8]
 [13 14 15 16]] 

 [13 14 15 16]

 [[0.07692308 0.14285714 0.2        0.25      ]
 [0.38461538 0.42857143 0.46666667 0.5       ]
 [0.69230769 0.71428571 0.73333333 0.75      ]
 [1.         1.         1.         1.        ]
 [1.30769231 1.28571429 1.26666667 1.25      ]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [35]:
import numpy as np
a=np.random.rand(10,3)             #crea un array 10x3 con numeri casuali tra 0 e 1
print("Array iniziale", a, "\n")
meno=np.abs(a-0.5)                 #calcola il valore assoluto della differenza tra i numeri dell'array e 0.5
print("Array -0.5", meno, "\n")
b=a[np.argmin(meno, axis=1), 1]    #trova l'indice del valore minimo della differenza per ogni riga e prende il secondo elemento di quella riga
print("Array dei numeri più vicini a 0.5", b)


Array iniziale [[0.66331154 0.31896867 0.18220999]
 [0.38987629 0.96934134 0.04149499]
 [0.26405023 0.48032561 0.56685863]
 [0.72737707 0.44997691 0.93916538]
 [0.53961896 0.0941217  0.98362201]
 [0.19088147 0.5660491  0.44250726]
 [0.87622246 0.62232142 0.32052372]
 [0.77997843 0.42323761 0.66305977]
 [0.88125066 0.73627978 0.81332998]
 [0.01800701 0.42425868 0.82443538]] 

Array -0.5 [[0.16331154 0.18103133 0.31779001]
 [0.11012371 0.46934134 0.45850501]
 [0.23594977 0.01967439 0.06685863]
 [0.22737707 0.05002309 0.43916538]
 [0.03961896 0.4058783  0.48362201]
 [0.30911853 0.0660491  0.05749274]
 [0.37622246 0.12232142 0.17947628]
 [0.27997843 0.07676239 0.16305977]
 [0.38125066 0.23627978 0.31332998]
 [0.48199299 0.07574132 0.32443538]] 

Array dei numeri più vicini a 0.5 [0.31896867 0.31896867 0.96934134 0.96934134 0.31896867 0.48032561
 0.96934134 0.96934134 0.96934134 0.96934134]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [36]:
import numpy as np
card=np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
print("Il valore minimo di oggi è stato: ", card.min())
print("Il valore massimo di oggi è stato: ", card.max())
sport=np.array([True if x>120 else False for x in card])      #seleziono solo i valori >120
print("La percentuale di volte che la frequenza cardiaca era >120 è stata: ", sport.mean(), "%")


Il valore minimo di oggi è stato:  60
Il valore massimo di oggi è stato:  164
La percentuale di volte che la frequenza cardiaca era >120 è stata:  0.5238095238095238 %


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [21]:
import numpy as np
#1
s=np.array([50000, 105250, 55000, 89000])
print("La somma degli stipendi è: ", s.sum())
#2
nuovo=s[1]*1.15         #nuovo stipendio del CEO
print("Il nuovo stipendio del CEO è: ", nuovo)
n=s               #creiamo una nuova copia dell'array
n[1]=nuovo        #sostituiamo il nuovo stipendio del CEO
print("I nuovi stipendi sono:", n)
#3
#Il valore è uguale
#4
print("\nCon dtype")
sd=np.array([50000, 105250, 55000, 89000], dtype=np.float64)
nuovo=sd[1]*1.15         #nuovo stipendio del CEO
print("Il nuovo stipendio del CEO è: ", nuovo)
n=sd               #creiamo una nuova copia dell'array
n[1]=nuovo                    #sostituiamo il nuovo stipendio del CEO
print("I nuovi stipendi sono:", n)
#5
nuovo=sd[0]*1.20         #nuovo stipendio della dipendente
print("\nIl nuovo stipendio della dipendente è: ", nuovo)
n[0]=nuovo        #sostituiamo il nuovo stipendio della dipendente
print("I nuovi stipendi sono:", n)
#6
nuovouno=sd[2]*1.10         #nuovo stipendio del dipendente uno
nuovodue=sd[3]*1.10         #nuovo stipendio del dipendente due
print("\nIl nuovo stipendio del dipendente uno è: ", nuovouno)
print("Il nuovo stipendio del dipendente due è: ", nuovodue)
n[2]=nuovouno        #sostituiamo il nuovo stipendio del dipendente uno
n[3]=nuovodue        #sostituiamo il nuovo stipendio del dipendente due
print("I nuovi stipendi sono:", n)
#7
print("\nIl costo totale degli stipendi è: ", n.sum())
print("E' costato all'azienda: ", n.sum()-s.sum())

La somma degli stipendi è:  299250
Il nuovo stipendio del CEO è:  121037.49999999999
I nuovi stipendi sono: [ 50000 121037  55000  89000]

Con dtype
Il nuovo stipendio del CEO è:  121037.49999999999
I nuovi stipendi sono: [ 50000.  121037.5  55000.   89000. ]

Il nuovo stipendio della dipendente è:  60000.0
I nuovi stipendi sono: [ 60000.  121037.5  55000.   89000. ]

Il nuovo stipendio del dipendente uno è:  60500.00000000001
Il nuovo stipendio del dipendente due è:  97900.00000000001
I nuovi stipendi sono: [ 60000.  121037.5  60500.   97900. ]

Il costo totale degli stipendi è:  339437.5
E' costato all'azienda:  24400.5


### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [37]:
import numpy as np
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])
#1
d=np.where(survey_matrix[::, 2]>=12)       # trova gli indici delle righe dove gli anni di istruzione sono maggiori o uguale a 12
print("Gli intervistati con almeno 12 anni di istruzione sono in posizione: ",d)
#2
print("I loro redditi sono: ", ( survey_matrix[d, 1]))
#3
print("Il reddito medio è: ", (survey_matrix[d, 1]).mean())

Gli intervistati con almeno 12 anni di istruzione sono in posizione:  (array([1, 2, 4]),)
I loro redditi sono:  [[52000 63000 58000]]
Il reddito medio è:  57666.666666666664


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [38]:
import numpy as np
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59], dtype=float)    #aggiungo dtype=float così posso usare la funzione nan
ages[ages==999]=np.nan                #sostituisco i valori 999 con NaN
print("Il cittadino più anziano ha %s anni" % np.nanmax(ages))

Il cittadino più anziano ha 112.0 anni


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [31]:
import random
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

frase=("\nIn epoche passate, viveva una donna saggia che era molto orgogliosa \ndell'antico __ che proteggeva. Quando un anziano del villaggio venne a \nchiederle consiglio su come garantire al meglio un raccolto abbondante e le \noffrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola \nparola, __.  \n\nRadunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli \nabitanti cercarono nella foresta un __.  \nNel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano \ncercando e tutti corsero dalla donna saggia per donarglielo.  \nCon un sorriso da un orecchio all’altro, e cantando canti di festa, la donna \nsaggia guardò i suoi compaesani e disse: 'Ora è giunto il tempo del banchetto \n- nessuno rimarrà mai più senza __!' \n\nCi fu grande gioia e celebrazione.")
parole=[random.choice(lista_parole) for i in range(5)]
print("Le parole sono: ", parole)

for parola in parole:
    frase=frase.replace("__", parola, 1)
print("\nLa frase è: ", frase)


Le parole sono:  ['IGNORANZA', 'RICEVIMENTO', 'IMPERO', 'CONSEGNA', 'BIOGRAFIA']

La frase è:  
In epoche passate, viveva una donna saggia che era molto orgogliosa 
dell'antico IGNORANZA che proteggeva. Quando un anziano del villaggio venne a 
chiederle consiglio su come garantire al meglio un raccolto abbondante e le 
offrì il RICEVIMENTO come dono, i suoi occhi si spalancarono e lei esclamò una sola 
parola, IMPERO.  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli 
abitanti cercarono nella foresta un CONSEGNA.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano 
cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna 
saggia guardò i suoi compaesani e disse: 'Ora è giunto il tempo del banchetto 
- nessuno rimarrà mai più senza BIOGRAFIA!' 

Ci fu grande gioia e celebrazione.


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."